# 데이터 전처리(Data Preprocessing) 

사이킷런의 머신러닝 알고리즘은 문자열 값을 입력 값으로 허용하지 않습니다.

모든 문자열 값은 인코딩되서 숫자 형으로 변환해야 합니다.

## 데이터 인코딩 

머신러닝을 위한 대표적인 인코딩 방식은 레이블 인코딩(Label encoding)과 원-핫 인코딩(One Hot encoding)이 있습니다.

먼저 레이블 인코딩은 카테고리 피처를 코드형 숫자 값으로 변환하는 것입니다.

###  레이블 인코딩

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

### LabelEncoder 객체 생성 후 fit()과 transform()으로 레이블 인코딩 수행 

In [8]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

In [9]:
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


TV는 0, 냉장고는 1, 전자레인지는 4, 컴퓨터는 5, 선풍기는 3, 믹서는 2로 변환됐습니다.

위 예제는 데이터가 작아서 문자열 값이 어떤 숫자로 인코딩됐는지 직관적으로 알 수 있지만, 많은 경우에는 알지 못합니다.

이 경우 LabelEncoder 객체의 classes_ 속성값으로 확인하면 됩니다.

In [10]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


inverse_transform()을 통해 인코딩 된 값을 다시 디코딩할 수 있습니다.

In [11]:
print('디코딩 원본 값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


레이블 인코딩은 간단하게 문자열 값을 숫자형 카테고리 값으로 변환합니다.

하지만 몇몇 ML 알고리즘에서는 예측 성능이 떨어지는 경우가 발생할 수 있습니다. 이는 숫자의 크고 작음에 대한 특성이 작용하기 때문입니다

원-핫 인코딩은 레이블 인코딩의 이러한 문제점을 해결하기 위한 인코딩 방식입니다.

### 원-핫 인코딩 

원-핫 인코딩은 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고 나머지 칼럼에는 0을 표시하는 방식입니다.

LabelEncoder와 다르게 주의할 점이 있습니다.

- OneHotEncoder로 변환 전 모든 문자열 값이 숫자형 값으로 변환되어야 함
- 입력 값으로 2차원 데이터가 필요

In [12]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [13]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

### 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환 

In [14]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

### 2차원 데이터로 변환 

In [15]:
labels = labels.reshape(-1, 1)

### 원-핫 인코딩 적용 

In [16]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [17]:
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


판다스에는 원-핫 인코딩을 더 쉽게 지원하는 API가 있습니다. get_dummies()를 이용하면 됩니다.

사이킷런의 OneHotEncoder와 다르게 문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환할 수 있습니다.

In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0