In [1]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)
np.ndim(A)

[1 2 3 4]


1

In [2]:
A.shape

(4,)

In [3]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)
np.ndim(B)

[[1 2]
 [3 4]
 [5 6]]


2

In [4]:
B.shape

(3, 2)

## 행렬 곱

In [6]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [8]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([7,8])
print(A.shape, B.shape)
np.dot(A, B)

(3, 2) (2,)


array([23, 53, 83])

In [10]:
X = np.array([1, 2])
W = np.array([[1, 3, 5], [2, 4, 6]])
print(X.shape, W.shape)
Y = np.dot(X, W)
print(Y)

(2,) (2, 3)
[ 5 11 17]
