## 소프트맥스 함수

In [1]:
import numpy as np
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
print(exp_a)
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)
y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [2]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

### 오버플로 방지하기
- 어떤 정수를 더해도 값이 바뀌지 않음을 이용
- 입력 신호 중 최댓값 이용

![image](https://user-images.githubusercontent.com/68543150/138800228-5ad21c6d-150e-47b7-a82e-5ab1088e9569.png)


In [4]:
a = np.array([1010, 1000, 990])
print(softmax(a))
c = np.max(a)
print(a - c)
print(softmax(a - c))

[nan nan nan]
[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


C:\Users\s_cwryu6252\.conda\envs\meetDeep\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
C:\Users\s_cwryu6252\.conda\envs\meetDeep\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [5]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

In [7]:
a = np.array([0.3, 2.9, 4.0])
print(softmax(a))
print(np.sum(softmax(a)))

[0.01821127 0.24519181 0.73659691]
1.0
