In [25]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3) # 정규분포로 초기화

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [26]:
net = simpleNet()
print(net.W)

x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])
p = net.predict(x)
print(p)
print(np.argmax(p))

net.loss(x, t)

[[ 1.36599457  0.65847522 -1.17188555]
 [ 0.73158056  0.81522051 -2.1655898 ]]
[ 1.47801924  1.12878359 -2.65216216]
0


4.673254511616955

In [27]:
net.W

array([[ 1.36599457,  0.65847522, -1.17188555],
       [ 0.73158056,  0.81522051, -2.1655898 ]])

In [28]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [22]:
f = lambda w: net.loss(x, t)
print(f())
dW = numerical_gradient(f, net.W)

NameError: name 'w' is not defined